import type { NextPage } from 'next'
import Head from 'next/head'
import Filter from '../src/components/Filter'
import FilterContainer from '../src/components/FilterContainer'
import ProductCard from '../src/components/ProductCard'
import ProductList from '../src/components/ProductList'
import ProductListHeader from '../src/components/ProductListHeader'
import { categoryFilter, priceFilter } from '../src/utils/filter'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductListHeader />
      <FilterContainer>
        <Filter title="Category" options={categoryFilter} />
        <Filter title="Price range" options={priceFilter} />
      </FilterContainer>
      <ProductList />
    </div>
  )
}

export default Home
